In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
df = pd.read_csv(url)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [2]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [4]:
df.shape

(344, 7)

In [5]:
df.dtypes

species                  str
island                   str
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                      str
dtype: object

In [6]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

df.head() shows first rows, defaults to 5, df.tail() works similarly

df.shape shows dimensions (rows, columns)

df.dtypes shows data type for each column

df.describe() shows summary stats for each numeric column

In [ ]:
# Prediction: table of species type
df["species"]

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: str

In [ ]:
# Prediction: table of integer counts of species type
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [10]:
# Prediction: boolean mask of body mass > 4500, equal rows to original
df["body_mass_g"] > 4500

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340     True
341     True
342     True
343     True
Name: body_mass_g, Length: 344, dtype: bool

In [11]:
# Prediction: rows where body mass > 4500, fewer rows than original
df[df["body_mass_g"] > 4500]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
39,Adelie,Dream,39.8,19.1,184.0,4650.0,MALE
45,Adelie,Dream,39.6,18.8,190.0,4600.0,MALE
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,MALE
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [12]:
df[(df["body_mass_g"] > 4500) & (df["island"] == "Dream")]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
39,Adelie,Dream,39.8,19.1,184.0,4650.0,MALE
45,Adelie,Dream,39.6,18.8,190.0,4600.0,MALE
181,Chinstrap,Dream,52.8,20.0,205.0,4550.0,MALE
189,Chinstrap,Dream,52.0,20.7,210.0,4800.0,MALE

In [14]:
# Objective: filter rows where sex is female
df[df["sex"] == "FEMALE"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,FEMALE
...,...,...,...,...,...,...,...
332,Gentoo,Biscoe,43.5,15.2,213.0,4650.0,FEMALE
334,Gentoo,Biscoe,46.2,14.1,217.0,4375.0,FEMALE
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE

In [16]:
# Objective: filter rows where body mass is < 3000 or > 5500
df[(df["body_mass_g"] > 5500) | (df["body_mass_g"] < 3000)]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,FEMALE
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,FEMALE
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,FEMALE
98,Adelie,Dream,33.1,16.1,178.0,2900.0,FEMALE
104,Adelie,Biscoe,37.9,18.6,193.0,2925.0,FEMALE
116,Adelie,Torgersen,38.6,17.0,188.0,2900.0,FEMALE
174,Chinstrap,Dream,43.2,16.6,187.0,2900.0,FEMALE
190,Chinstrap,Dream,46.9,16.6,192.0,2700.0,FEMALE
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,MALE
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,MALE
231,Gentoo,Biscoe,49.0,16.1,216.0,5550.0,MALE
233,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,MALE
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,MALE
237,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,MALE
240,Gentoo,Biscoe,50.2,14.3,218.0,5700.0,MALE
247,Gentoo,Biscoe,47.8,15.0,215.0,5650.0,MALE
249,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,MALE
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,MALE
261,Gentoo,Biscoe,49.6,16.0,225.0,5700.0,MALE
264,Gentoo,Biscoe,50.5,15.9,222.0,5550.0,MALE
279,Gentoo,Biscoe,50.4,15.3,224.0,5550.0,MALE
283,Gentoo,Biscoe,54.3,15.7,231.0,5650.0,MALE
285,Gentoo,Biscoe,49.8,16.8,230.0,5700.0,MALE
287,Gentoo,Biscoe,49.5,16.2,229.0,5800.0,MALE
289,Gentoo,Biscoe,50.7,15.0,223.0,5550.0,MALE
295,Gentoo,Biscoe,48.6,16.0,230.0,5800.0,MALE
297,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,MALE
299,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,MALE
305,Gentoo,Biscoe,50.8,17.3,228.0,5600.0,MALE
309,Gentoo,Biscoe,52.1,17.0,230.0,5550.0,MALE
313,Gentoo,Biscoe,49.5,16.1,224.0,5650.0,MALE
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,MALE
331,Gentoo,Biscoe,49.8,15.9,229.0,5950.0,MALE
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE

In [17]:
df.sort_values("body_mass_g")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
190,Chinstrap,Dream,46.9,16.6,192.0,2700.0,FEMALE
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,FEMALE
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,FEMALE
116,Adelie,Torgersen,38.6,17.0,188.0,2900.0,FEMALE
98,Adelie,Dream,33.1,16.1,178.0,2900.0,FEMALE
...,...,...,...,...,...,...,...
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,MALE
237,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,MALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [18]:
# Objective: return table of five heaviest penguins
df.sort_values("body_mass_g", ascending=False).head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
237,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,MALE
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,MALE
297,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,MALE
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
331,Gentoo,Biscoe,49.8,15.9,229.0,5950.0,MALE

Question: Which island's penguins are heaviest on average?

In [24]:
# Description: sort the data by island and return a table of each island's mean body mass

island_means = df.groupby("island")["body_mass_g"].mean()
island_means.idxmax()

'Biscoe'