In [1]:
import pandas as pd
import numpy as np

csv_text = """occupation, median_wage, employment
Software Developer, 132270, 1656880
Registered Nurse , 86070, 3175390
Cashier, 29720, 3298660
Data Scientist, 108020, N/A
 Economist, 115730, 16680
Truck Driver, 54320, 2044400
Teacher, N/A, 2291249
"""

with open("messy_wages.csv", "w") as f:
    f.write(csv_text)

In [2]:
wages = pd.read_csv("messy_wages.csv")
wages

           occupation  median_wage  employment
0  Software Developer       132270     1656880
1   Registered Nurse         86070     3175390
2             Cashier        29720     3298660
3      Data Scientist       108020         N/A
4           Economist       115730       16680
5        Truck Driver        54320     2044400
6             Teacher          N/A     2291249

In [5]:
wages.head()

           occupation  median_wage  employment
0  Software Developer       132270     1656880
1   Registered Nurse         86070     3175390
2             Cashier        29720     3298660
3      Data Scientist       108020         N/A
4           Economist       115730       16680

In [6]:
wages.shape

(7, 3)

In [7]:
wages.dtypes

occupation      str
 median_wage    str
 employment     str
dtype: object

In [8]:
wages.describe()

                occupation  median_wage  employment
count                    7            7           7
unique                   7            7           7
top     Software Developer       132270     1656880
freq                     1            1           1

In [9]:
wages.columns.tolist()

['occupation', ' median_wage', ' employment']

In [10]:
wages["occupation"].values

<StringArray>
['Software Developer',  'Registered Nurse ',            'Cashier',
     'Data Scientist',         ' Economist',       'Truck Driver',
            'Teacher']
Length: 7, dtype: str

Problems with the data:
- Data scientist has N/A for employment
- Teacher has N/A for median_wage
- The wage and employment are strs not ints
- Spaces in column names and values

In [12]:
wages.columns = wages.columns.str.strip()

In [13]:
wages.columns

Index(['occupation', 'median_wage', 'employment'], dtype='str')

In [16]:
wages["median_wage"]

0     132270
1      86070
2      29720
3     108020
4     115730
5      54320
6        N/A
Name: median_wage, dtype: str

In [17]:
wages["occupation"] = wages["occupation"].str.strip()

In [19]:
wages["median_wage"] = pd.to_numeric(wages["median_wage"], errors="coerce")

In [20]:
wages["employment"] = pd.to_numeric(wages["employment"], errors="coerce")

In [21]:
wages.isna()

   occupation  median_wage  employment
0       False        False       False
1       False        False       False
2       False        False       False
3       False        False        True
4       False        False       False
5       False        False       False
6       False         True       False

In [22]:
wages.isna().sum()

occupation     0
median_wage    1
employment     1
dtype: int64

In [ ]:
wages.dropna()

           occupation  median_wage  employment
0  Software Developer     132270.0   1656880.0
1    Registered Nurse      86070.0   3175390.0
2             Cashier      29720.0   3298660.0
4           Economist     115730.0     16680.0
5        Truck Driver      54320.0   2044400.0

### Cleaning Pipeline

In [26]:
wages = pd.read_csv("messy_wages.csv")
wages.columns = wages.columns.str.strip()
wages["occupation"] = wages["occupation"].str.strip()
wages["median_wage"] = pd.to_numeric(wages["median_wage"], errors="coerce")
wages["employment"] = pd.to_numeric(wages["employment"], errors="coerce")
wages

           occupation  median_wage  employment
0  Software Developer     132270.0   1656880.0
1    Registered Nurse      86070.0   3175390.0
2             Cashier      29720.0   3298660.0
3      Data Scientist     108020.0         NaN
4           Economist     115730.0     16680.0
5        Truck Driver      54320.0   2044400.0
6             Teacher          NaN   2291249.0