In [1]:
import pandas as pd, numpy as np, base64
blob = b"b2NjX2NvZGUsIG9jY3VwYXRpb25fdGl0bGUsbWVkaWFuX3dhZ2UsdG90YWxfZW1wbG95bWVudCxtZWFuX3dhZ2UKMTUtMTI1MiwgU29mdHdhcmUgRGV2ZWxvcGVycywxMzIyNzAsIDE2NTY4ODAsMTM4MTEwCjI5LTExNDEsUmVnaXN0ZXJlZCBOdXJzZXMgLDg2MDcwLDMxNzUzOTAsOTQ0ODAKNDEtMjAxMSxDYXNoaWVycywyOTcyMCwzMjk4NjYwLDMxNjEwCjE1LTIwNTEsRGF0YSBTY2llbnRpc3RzLDEwODAyMCwqKiwxMTk4NDAKMTktMzAxMSwgRWNvbm9taXN0cywxMTU3MzAsMTY2ODAsMTMxMzcwCjUzLTMwMzIsVHJ1Y2sgRHJpdmVycyw1NDMyMCwyMDQ0NDAwLDU2MDIwCjI1LTIwMjEsRWxlbWVudGFyeSBUZWFjaGVycywqKiwyMjkxMjQ5LDY2NDcwCjE1LTEyNTIsIFNvZnR3YXJlIERldmVsb3BlcnMsMTMyMjcwLCAxNjU2ODgwLDEzODExMAo="
open("mystery_bls.csv", "wb").write(base64.b64decode(blob))
print("mystery_bls.csv written - begin diagnosis")

mystery_bls.csv written - begin diagnosis

In [2]:
mystery = pd.read_csv("mystery_bls.csv")
mystery

  occ_code      occupation_title median_wage total_employment  mean_wage
0  15-1252   Software Developers      132270          1656880     138110
1  29-1141    Registered Nurses        86070          3175390      94480
2  41-2011              Cashiers       29720          3298660      31610
3  15-2051       Data Scientists      108020               **     119840
4  19-3011            Economists      115730            16680     131370
5  53-3032         Truck Drivers       54320          2044400      56020
6  25-2021   Elementary Teachers          **          2291249      66470
7  15-1252   Software Developers      132270          1656880     138110

In [3]:
mystery.shape

(8, 5)

In [4]:
mystery.dtypes

occ_code               str
 occupation_title      str
median_wage            str
total_employment       str
mean_wage            int64
dtype: object

In [5]:
mystery.describe()

           mean_wage
count       8.000000
mean    97001.250000
std     41363.666747
min     31610.000000
25%     63857.500000
50%    107160.000000
75%    133055.000000
max    138110.000000

In [6]:
mystery.columns.to_list()

['occ_code',
 ' occupation_title',
 'median_wage',
 'total_employment',
 'mean_wage']

In [7]:
mystery.columns = mystery.columns.str.strip()

In [8]:
mystery["occupation_title"].values

<StringArray>
[' Software Developers',   'Registered Nurses ',             'Cashiers',
      'Data Scientists',          ' Economists',        'Truck Drivers',
  'Elementary Teachers', ' Software Developers']
Length: 8, dtype: str

In [9]:
mystery["occupation_title"] = mystery["occupation_title"].str.strip()

In [10]:
mystery["median_wage"].values

<StringArray>
['132270', '86070', '29720', '108020', '115730', '54320', '**', '132270']
Length: 8, dtype: str

In [11]:
mystery["median_wage"] = pd.to_numeric(mystery["median_wage"], errors="coerce")

In [12]:
mystery["total_employment"] = pd.to_numeric(mystery["total_employment"], errors="coerce")

In [13]:
mystery.isna()

   occ_code  occupation_title  median_wage  total_employment  mean_wage
0     False             False        False             False      False
1     False             False        False             False      False
2     False             False        False             False      False
3     False             False        False              True      False
4     False             False        False             False      False
5     False             False        False             False      False
6     False             False         True             False      False
7     False             False        False             False      False

In [14]:
mystery.dropna()

  occ_code     occupation_title  median_wage  total_employment  mean_wage
0  15-1252  Software Developers     132270.0         1656880.0     138110
1  29-1141    Registered Nurses      86070.0         3175390.0      94480
2  41-2011             Cashiers      29720.0         3298660.0      31610
4  19-3011           Economists     115730.0           16680.0     131370
5  53-3032        Truck Drivers      54320.0         2044400.0      56020
7  15-1252  Software Developers     132270.0         1656880.0     138110

### Cleaning Pipeline

In [16]:
mystery = pd.read_csv("mystery_bls.csv")
mystery.columns = mystery.columns.str.strip()
mystery["occupation_title"] = mystery["occupation_title"].str.strip()
mystery["median_wage"] = pd.to_numeric(mystery["median_wage"], errors="coerce")
mystery["total_employment"] = pd.to_numeric(mystery["total_employment"], errors="coerce")
mystery = mystery.drop_duplicates()
mystery

  occ_code     occupation_title  median_wage  total_employment  mean_wage
0  15-1252  Software Developers     132270.0         1656880.0     138110
1  29-1141    Registered Nurses      86070.0         3175390.0      94480
2  41-2011             Cashiers      29720.0         3298660.0      31610
3  15-2051      Data Scientists     108020.0               NaN     119840
4  19-3011           Economists     115730.0           16680.0     131370
5  53-3032        Truck Drivers      54320.0         2044400.0      56020
6  25-2021  Elementary Teachers          NaN         2291249.0      66470

### Data cleaning notes - mystery_bls.csv, 8 rows x 5 columns as received
- Column names contained stray whitespace (e.g. ' median_wage'); stripped
- Occupation titles contained leading/trailing whitespace in 3 of 8 rows; stripped
- `median_wage` and `total_employment` loaded as text because missing values were coded as text; coerced to numeric with '**' -> NaN
- Duplicate row (Software Developers, 15-1252) appeared twice; deduplicated, 8 -> 7 rows
- After coercion, 2 of 7 rows had one missing value each (Data Scientists: employment; Elementary Teachers: wage); **decided** to drop both, 7 -> 5 rows, to work with complete cases; cost: analysis loses one large high-wage occupation and one large public-sector one; alternative: retain rows and use NaN-aware operations